# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\tmypackage\";\n\x04\x44\x61ta\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0f\n\x07voltage\x18\x02 \x01(\x01\x12\x0f\n\x07\x63urrent\x18\x03 \x01(\x01\"R\n\x04\x42\x65ss\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x1d\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x0f.mypackage.Data\",\n\x0b\x42\x65ssRequest\x12\x1d\n\x04\x62\x65ss\x18\x01 \x01(\x0b\x32\x0f.mypackage.Bess\"\x1f\n\x0c\x42\x65ssResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\x0b\x42\x65ssService\x12>\n\x0bProcessBess\x12\x16.mypackage.BessRequest\x1a\x17.mypackage.BessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=25
  _globals['_DATA']._serialized_end=84
  _globals['_BESS']._serialized_start=86
  _globals['_BESS']._serialized_end=168
  _globals['_BESSREQUEST']._serialized_start=170
  _globals['_BESSREQUEST']._serialized_end=214
  _globals['_BESSRESPONSE']._serialized_start=216
  _globals['_BESSRESPONSE']._serialized_end=247
  _globals['_BESSSERVICE']._serialized_start=249
  _globals['_BESSSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
